### ISSUE TITLE
Validation feedback and css class "error" per field

### ISSUE THREAD

**Issue by mcmulman** [alexgunkel/fe_useradd#1]
Required fields should be marked.
Negative validated field should be market with the class "error" and with a feedback text.

**Comment by alexgunkel** [comment]
rtfm:
https://fluidtypo3.org/viewhelpers/fluid/master/Form/TextfieldViewHelper.html
https://fluidtypo3.org/viewhelpers/fluid/master/Form/ValidationResultsViewHelper.html
