### ISSUE TITLE
Make company and position visible in user account (BE)

### ISSUE THREAD

**Issue by mcmulman** [alexgunkel/fe_useradd#4]

**Comment by alexgunkel** [comment]
I don't see the gender field in my fe_user-entries. Is it possible that it's provided by some other extension you activated in your TYPO3 installation?

**Comment by mcmulman** [comment]
You're right. I didn't see it in the documentation, but the extension femanager added some fields (e.g. gender):
https://github.com/in2code-de/femanager/blob/develop/ext_tables.sql

Is it possible to write it into this fields?

So maybe "femanager" should be a requirement for "fe_useradd"?!
